# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ManyToManyField(to='events.City'),
        ),
    ]
