# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.TextField()),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('github', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'employees',
            },
        ),
    ]
